jsub: split_l(): the generator should return silently
Instead of the generator raising an exception, have it return silently.

This prevents this traceback:

=== 8< ===
Traceback (most recent call last):
  File "/home/arturo/git/wmf/labs/toollabs/jobutils/bin/jsub", line 186, in split_l
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arturo/git/wmf/labs/toollabs/jobutils/bin/jsub", line 663, in <module>
    main()
  File "/home/arturo/git/wmf/labs/toollabs/jobutils/bin/jsub", line 555, in main
    args = build_parser().parse_args(namespace=args)
  File "/usr/lib/python3.9/argparse.py", line 1830, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 1863, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2072, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.9/argparse.py", line 2012, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1924, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.9/argparse.py", line 2473, in _get_values
    value = [self._get_value(action, v) for v in arg_strings]
  File "/usr/lib/python3.9/argparse.py", line 2473, in <listcomp>
    value = [self._get_value(action, v) for v in arg_strings]
  File "/usr/lib/python3.9/argparse.py", line 2488, in _get_value
    result = type_func(arg_string)
  File "/home/arturo/git/wmf/labs/toollabs/jobutils/bin/jsub", line 191, in argparse_resource
    for label, val in split_l(value):
RuntimeError: generator raised StopIteration
=== 8< ===

Bug: T278748
Signed-off-by: Arturo Borrero Gonzalez <aborrero@wikimedia.org>
Change-Id: I3bdaf40bc1ab0c926426378f76871d6d2e5095e2